name: ci

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - 
        name: tag
        uses: anothrNick/github-tag-action@1.61.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true   
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.17.1
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            knutia/fast-realip:latest
            knutia/fast-realip:${{ steps.tag.outputs.new_tag }}
      -
        name: Create release notes
        id: release_notes
        run: gh release create ${{ steps.tag.outputs.new_tag }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
